User:
  name: Aquiles
  role: Teacher

DAQ:
  name: Arduino
  port: /dev/ttyACM0

Scan:
  start: 0V
  stop: 3.3V
  step: 100mV
  channel_out: 0
  channel_in: 0
  delay: 100ms

Save_File:
  filename: data_