User: me
init:
  devices: Config/devices.yml
DAQ:
  name: DummyDaq
  port: /dev/ttyACM0
  model: v1.0

Scan:
  port_in: 0
  port_out: 0
  start: 0.V
  stop: 3.3V
  step: 1.V
  delay: 200ms
  refresh_time: 100ms

Monitor:
  port: 1
  time_resolution: 1ms
  refresh_time: 100ms
  total_time: 15s