ao:
  1:
    name:         Channel 1
    upper_limit:  5.4       # (Volt)
    lower_limit:  -5.4      # (Volt)
  2:
    name:         Channel 2
    upper_limit:  5.4       # (Volt)
    lower_limit:  -5.4      # (Volt)
monitor:
  time_step:        0.050   # (s) Note that the basic analog approach doesn't really go faster than 0.010 seconds
  plot_points:      110
  1:
    name:           Channel 1
  2:
    name:           Channel 2
  gui_refresh_time: .01     # (s) How often gui checks if here's new data (usually quicker than time_step)
  stop_timeout:     1       # (s) How much time to give monitor to stop before forcefully terminating it